4.1 update python info
neo4j/driver-documentation pull request #138
Opened 2020-06-25 13:25 UTC by AlexicaWright

2020-06-25 13:32 UTC, gjmwoods approved these changes

2020-06-25 13:47 UTC, davidoliverSP2 requested changes
Thanks @AlexicaWright 

A coupe of suggested changes for the information about versions.
I also spotted a typo elsewhere, and suggested a change.

2020-06-25 13:47 UTC, davidoliverSP2 commented on asciidoc/get-started.adoc
> +For information, see For information, see https://neo4j.com/docs/migration-guide/4.0/upgrade-driver/[4.0 Migration Guide -> Chapter 6. Upgrade Neo4j drivers].
```suggestion
For information, see https://neo4j.com/docs/migration-guide/4.0/upgrade-driver/[4.0 Migration Guide -> Chapter 6. Upgrade Neo4j drivers].
```

2020-06-25 13:47 UTC, davidoliverSP2 commented on asciidoc/get-started.adoc
> +The 4.1 release of the Go and Python drivers is a work in progress. There is currently no release date available.
```suggestion
The 4.1 Go and Python drivers are a work in progress. 
There is currently no release date available.
```

2020-06-25 13:47 UTC, davidoliverSP2 commented on asciidoc/get-started.adoc
> +For more information on the 4.0 Python Driver, see {docs-base-uri}/driver-manual/4.0.
```suggestion
The latest Go Driver is 1.8.
For information on the 1.8 Go Driver, see {docs-base-uri}/driver-manual/1.7.

The latest Python Driver is 4.0.
For information on the 4.0 Python Driver, see {docs-base-uri}/driver-manual/4.0.
```

2020-06-26 08:36 UTC, davidoliverSP2 approved these changes

2020-06-26 12:00 UTC, merged