update to Antora package
neo4j/driver-documentation pull request #296
Opened 2022-08-23 18:03 UTC by recrwplay

See #295 for notes and details

2022-08-24 13:12 UTC, davidoliverSP2 requested changes
Hey @recrwplay 

Couple of things to investigate here:
I'm getting some missing images on the Client Applications page of all manuals, and the Python Manual has no content on the Session API page....

2022-08-24 13:47 UTC, recrwplay commented
I think the png files in common-content might have been corrupted when Gradle copied them. I think I've seen that happen before.

Python Sessions had some duplicate files which were messing up the output. 

Should be resolved now.

2022-08-25 13:09 UTC, davidoliverSP2 approved these changes

2022-08-25 13:09 UTC, davidoliverSP2 commented
This looks good to me now 🎉

2022-08-30 12:30 UTC, merged