Add cross reference to Ops Man on routing config
neo4j/driver-documentation pull request #38
Opened 2017-08-23 14:08 UTC by mariascharin

2017-08-24 07:09 UTC, mariascharin commented
Corresponding ref in the other direction: https://github.com/neo-technology/neo4j-manual-modeling/pull/310

2017-08-24 14:08 UTC, technige approved these changes

2017-08-25 09:26 UTC, jjaderberg requested changes
A routing driver is any driver that uses `bolt+routing` protocol to connect to a Causal Cluster, it doesn't have to be a multi-dc cluster. This note gives the impression that routing and load balancing is the same thing as the multi-dc routing policy feature, but there is already the routing of reads and writes in a cluster, and there is basic load balancing in that servers will be selected from the routing table with some rotation when creating new sessions (round robin I guess). These features are part of any CC+routing driver setup, whether it's multi-dc or not.

2017-08-29 08:45 UTC, jjaderberg approved these changes

2017-08-29 12:59 UTC, merged